<?php
$xpdo_meta_map = array (
    'version' => '3.0',
    'namespace' => 'Brevis\\Model',
    'class_map' => 
    array (
        'xPDO\\Om\\xPDOSimpleObject' => 
        array (
            0 => 'Brevis\\Model\\Category',
            1 => 'Brevis\\Model\\Element',
            2 => 'Brevis\\Model\\BodyType',
            3 => 'Brevis\\Model\\Increase',
            4 => 'Brevis\\Model\\Cars',
            5 => 'Brevis\\Model\\MarkAlias',
            6 => 'Brevis\\Model\\Condition',
            7 => 'Brevis\\Model\\Item',
            8 => 'Brevis\\Model\\ItemImages',
            9 => 'Brevis\\Model\\Sklad',
            10 => 'Brevis\\Model\\SkladStatus',
            11 => 'Brevis\\Model\\User',
            12 => 'Brevis\\Model\\UserHauthService',
            13 => 'Brevis\\Model\\UserSession',
            14 => 'Brevis\\Model\\BuyerLevel',
            15 => 'Brevis\\Model\\Group',
            16 => 'Brevis\\Model\\UserGroupMember',
            17 => 'Brevis\\Model\\Permissions',
            18 => 'Brevis\\Model\\GroupPermissions',
            19 => 'Brevis\\Model\\Country',
            20 => 'Brevis\\Model\\Region',
            21 => 'Brevis\\Model\\City',
            22 => 'Brevis\\Model\\Supplier',
            23 => 'Brevis\\Model\\SupplierStatus',
            24 => 'Brevis\\Model\\SupplierPermission',
            25 => 'Brevis\\Model\\Order',
            26 => 'Brevis\\Model\\OrderStatus',
            27 => 'Brevis\\Model\\EventLog',
            28 => 'Brevis\\Model\\PaymentType',
            29 => 'Brevis\\Model\\Payment',
            30 => 'Brevis\\Model\\FeeType',
            31 => 'Brevis\\Model\\Fee',
            32 => 'Brevis\\Model\\ApiKey',
        ),
    ),
);