<?php

$_lang['item.id'] = 'ID';
$_lang['item.mark'] = $_lang['item.mark_key'] = 'Марка';
$_lang['item.model'] = $_lang['item.model_key'] = 'Модель';
$_lang['item.year_key'] = 'Модификация';
$_lang['item.category'] = $_lang['item.category_key'] = 'Категория';
$_lang['item.element'] = $_lang['item.element_key'] = 'Элемент';
$_lang['item.name'] = 'Наименование детали';
$_lang['item.body_type'] = 'Тип кузова';
$_lang['item.body_type_desc'] = 'Укажите, если у товара есть различия для разных кузовов.';
$_lang['item.kol'] = 'Количество деталей';
$_lang['item.price'] = 'Цена';
$_lang['item.code'] = 'Код';
$_lang['item.vendor_code'] = 'Артикул (код производителя)';
$_lang['item.updatedon'] = 'Обновлено';
$_lang['item.condition'] = 'Состояние детали';
$_lang['item.condition_option'] = '{$name}. Износ {$id}%';
$_lang['item.condition_comment'] = 'Комментарий к состоянию детали';
$_lang['item.comment'] = 'Комментарий';
$_lang['item.comment_desc'] = 'Любая дополнительная информация.';
$_lang['item.error'] = 'Ошибка';
$_lang['item.sklad_id'] = $_lang['item.sklad_prefix'] = 'Склад';
$_lang['item.published'] = 'Опубликован';
$_lang['item.reserved'] = 'Зарезервировано в заказе';
$_lang['item.source'] = 'Источник данных';
$_lang['item.moderate'] = 'Одобрен';
$_lang['item.moderate.wait'] = 'Ожидает';
$_lang['item.moderate.yes'] = 'Да';
$_lang['item.moderate.no'] = 'Отказ';
$_lang['item.moderate_message'] = 'Причина отказа или иное сообщение пользователю';
$_lang['item.one_sklad_needed'] = 'Необходимо завести хотя бы один склад.';
$_lang['item.upload_later_desc'] = 'Вы сможете загрузить фотографии после первого сохранения товара.';
$_lang['item.images'] = 'Фотографии';
$_lang['item.upload_images'] = 'Загрузить фотографии';
$_lang['item.upload'] = 'Загрузить';
$_lang['item.sticker'] = 'Стикер';
$_lang['item.statusMessage'] = 'Все товары проходят предварительную модерацию после добавления/изменения.';
$_lang['item.confirm_remove'] = 'Подтвердите удаление (необратимо).';
$_lang['item.error.published_no_photo'] = 'Нельзя публиковать позиции без фотографий.';