<?php

$_lang['supplier.user_id'] = $_lang['supplier.user_name'] = 'Пользователь';
$_lang['supplier.name'] = 'Название поставщика';
$_lang['supplier.user_name'] = 'Пользователь';
$_lang['supplier.code'] = 'Код поставщика';
$_lang['supplier.status_id'] = $_lang['supplier.status_name'] = 'Статус';
$_lang['supplier.status_message'] = 'Сообщение статуса';
$_lang['supplier.status_message_help'] = 'Ваш комментарий к статусу.';
$_lang['supplier.status_notify'] = 'Уведомить пользователя о смене статуса.';
$_lang['supplier.user_pos'] = 'Должность пользователя в организации';
$_lang['supplier.your_pos'] = 'Ваша должность в организации';
$_lang['supplier.company_name'] = 'Название организации';
$_lang['supplier.country_id'] = 'Страна';
$_lang['supplier.country'] = 'Страна';
$_lang['supplier.region_id'] = 'Регион';
$_lang['supplier.region'] = 'Регион';
$_lang['supplier.city_id'] = 'Город';
$_lang['supplier.city'] = 'Город';
$_lang['supplier.index'] = 'Почтовый индекс';
$_lang['supplier.legal_address'] = 'Юридический адрес';
$_lang['supplier.actual_address'] = 'Фактический адрес';
$_lang['supplier.email'] = 'Электронный адрес организации';
$_lang['supplier.phone'] = 'Телефон';
$_lang['supplier.fax'] = 'Факс';	
$_lang['supplier.inn'] = 'ИНН';
$_lang['supplier.kpp'] = 'КПП';
$_lang['supplier.dir_name'] = 'ФИО директора';
$_lang['supplier.buch_name'] = 'ФИО главного бухгалтера';
$_lang['supplier.bank_name'] = 'Название банка';
$_lang['supplier.bik'] = 'БИК';
$_lang['supplier.r_schet'] = 'Расчетный счет';
$_lang['supplier.k_schet'] = 'Корреспондентский счет';
$_lang['supplier.okved'] = 'ОКВЭД';
$_lang['supplier.okpo'] = 'ОКПО';
$_lang['supplier.ogrn'] = 'ОГРН';
$_lang['supplier.comment'] = 'Комментарий';
$_lang['supplier.sklad_count'] = 'Кол-во складов';
$_lang['supplier.id'] = 'Код (ID)';